
[general]
	#Enable logging of allowed structures. This is on by default. If you use this on a server and dont want to waste space with constant spam turn it off.
	log-allowed-structures = false
	#Enable logging of prevented structures. This is on by default. If you use this on a server and dont want to waste space with constant spam turn it off.
	log-prevented-structures = false
	#Enable debug logging. This is on by default. If you use this on a server and dont want to waste space with constant spam turn it off.
	debug = false

